# Generated by Django 5.0.1 on 2024-02-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
        migrations.CreateModel(
            name='MenuNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Direct URL')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('containing_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='treemenuapp.menu', verbose_name='Menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='treemenuapp.menunode', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'menu node',
                'verbose_name_plural': 'menu nodes',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemenuapp.menunode', verbose_name='Root item'),
        ),
    ]
