# Generated by Django 5.0.1 on 2024-02-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menunode',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Direct URL'),
        ),
    ]
