# Generated by Django 5.0.1 on 2024-02-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemenuapp', '0003_rename_containing_menu_menunode_menu_alter_menu_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
