# Generated by Django 5.0.1 on 2024-02-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenuapp', '0004_remove_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='named_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Named URL'),
        ),
        migrations.AlterField(
            model_name='menunode',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direct URL'),
        ),
    ]
