# Generated by Django 5.0.1 on 2024-02-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenuapp', '0005_menunode_named_url_alter_menunode_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='root',
        ),
        migrations.AlterField(
            model_name='menunode',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='treemenuapp.menu', verbose_name='Menu'),
        ),
    ]
